using System; using System.Data;
namespace NeptunoLab05 { public static class PreviewData { public static DataSet Create() { var ds = new DataSet(); DataTable t;
t = new DataTable("Categorias");
t.Columns.Add("CategoriaID", typeof(int));
t.Columns.Add("NombreCategoria", typeof(string));
t.Columns.Add("Descripcion", typeof(string));
t.Columns.Add("Activo", typeof(bool));
t.Rows.Add(1,"Bebidas","Refrescos, cafés, tés, cervezas y otras bebidas",true);
t.Rows.Add(2,"Condimentos","Salsas, especias y aderezos",true);
t.Rows.Add(3,"Confituras","Mermeladas, dulces y postres",true);
t.Rows.Add(4,"Lácteos","Quesos y otros productos lácteos",true);
t.Rows.Add(5,"Carnes y Embutidos","Carnes preparadas y embutidos",true);
ds.Tables.Add(t);
t = new DataTable("Proveedores");
t.Columns.Add("ProveedorID", typeof(int));
t.Columns.Add("CompaniaNombre", typeof(string));
t.Columns.Add("NombreContacto", typeof(string));
t.Columns.Add("CargoContacto", typeof(string));
t.Columns.Add("Direccion", typeof(string));
t.Columns.Add("Ciudad", typeof(string));
t.Columns.Add("CodigoPostal", typeof(string));
t.Columns.Add("Pais", typeof(string));
t.Columns.Add("Telefono", typeof(string));
t.Columns.Add("Fax", typeof(string));
t.Columns.Add("Activo", typeof(bool));
t.Rows.Add(1,"Lácteos García S.A.","Ana García","Gerente de Ventas","Av. Los Álamos 245","Lima","15024","Perú","511-4567890","511-4567891",true);
t.Rows.Add(2,"Bebidas del Sur Ltda.","Carlos Ramírez","Jefe Comercial","Jr. Comercio 890","Arequipa","04001","Perú","054-223344","054-223345",true);
t.Rows.Add(3,"Embutidos La Preferida","María Torres","Coordinadora de Distribución","Calle Las Flores 120","Trujillo","13001","Perú","044-556677","044-556678",true);
t.Rows.Add(4,"Condimentos Andinos SAC","Jorge Quispe","Gerente General","Av. Industrial 500","Cusco","08001","Perú","084-778899","084-778900",true);
t.Rows.Add(5,"Dulces del Valle E.I.R.L.","Lucía Fernández","Encargada de Ventas","Jr. San Martín 77","Chiclayo","14001","Perú","074-991122","074-991123",true);
ds.Tables.Add(t);
t = new DataTable("Clientes");
t.Columns.Add("ClienteID", typeof(int));
t.Columns.Add("Empresa", typeof(string));
t.Columns.Add("NombreContacto", typeof(string));
t.Columns.Add("Ciudad", typeof(string));
t.Columns.Add("Pais", typeof(string));
t.Columns.Add("Telefono", typeof(string));
t.Rows.Add(1,"Comercial Andina SAC","Pedro Salazar","Lima","Perú","511-2345678");
t.Rows.Add(2,"Supermercados del Norte","Rosa Medina","Trujillo","Perú","044-334455");
t.Rows.Add(3,"Distribuidora Sureña EIRL","Luis Chávez","Arequipa","Perú","054-667788");
t.Rows.Add(4,"Minimarket Central","Elena Rojas","Cusco","Perú","084-112233");
t.Rows.Add(5,"Tiendas Express SAC","Miguel Ángel Paredes","Chiclayo","Perú","074-445566");
ds.Tables.Add(t);
t = new DataTable("Empleados");
t.Columns.Add("EmpleadoID", typeof(int));
t.Columns.Add("Nombre", typeof(string));
t.Columns.Add("Apellidos", typeof(string));
t.Columns.Add("Cargo", typeof(string));
t.Columns.Add("FechaNacimiento", typeof(DateTime));
t.Columns.Add("FechaContratacion", typeof(DateTime));
t.Columns.Add("Ciudad", typeof(string));
t.Columns.Add("Pais", typeof(string));
t.Rows.Add(1,"Juan","Pérez Gómez","Vendedor",DateTime.Parse("1990-05-12", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2020-01-15", System.Globalization.CultureInfo.InvariantCulture),"Lima","Perú");
t.Rows.Add(2,"María","López Díaz","Supervisora de Ventas",DateTime.Parse("1988-09-23", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2018-03-01", System.Globalization.CultureInfo.InvariantCulture),"Lima","Perú");
t.Rows.Add(3,"Carlos","Ruiz Mendoza","Vendedor",DateTime.Parse("1992-02-17", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2021-06-10", System.Globalization.CultureInfo.InvariantCulture),"Arequipa","Perú");
t.Rows.Add(4,"Sofía","Vargas Castro","Gerente Regional",DateTime.Parse("1985-11-30", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2015-08-20", System.Globalization.CultureInfo.InvariantCulture),"Trujillo","Perú");
t.Rows.Add(5,"Diego","Fernández Ríos","Vendedor",DateTime.Parse("1995-07-08", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2022-02-01", System.Globalization.CultureInfo.InvariantCulture),"Cusco","Perú");
ds.Tables.Add(t);
t = new DataTable("Transportistas");
t.Columns.Add("TransportistaID", typeof(int));
t.Columns.Add("CompaniaNombre", typeof(string));
t.Columns.Add("Telefono", typeof(string));
t.Rows.Add(1,"Transportes Rápido SAC","511-8889900");
t.Rows.Add(2,"Envíos Seguros EIRL","511-7776655");
t.Rows.Add(3,"Logística del Pacífico","054-990011");
t.Rows.Add(4,"Courier Nacional SA","044-223344");
t.Rows.Add(5,"TransAndino Express","084-556677");
ds.Tables.Add(t);
t = new DataTable("Productos");
t.Columns.Add("ProductoID", typeof(int));
t.Columns.Add("NombreProducto", typeof(string));
t.Columns.Add("ProveedorID", typeof(int));
t.Columns.Add("CategoriaID", typeof(int));
t.Columns.Add("CantidadPorUnidad", typeof(string));
t.Columns.Add("PrecioUnidad", typeof(decimal));
t.Columns.Add("UnidadesEnExistencia", typeof(int));
t.Columns.Add("UnidadesEnPedido", typeof(int));
t.Columns.Add("NivelDeReorden", typeof(int));
t.Columns.Add("Descontinuado", typeof(bool));
t.Columns.Add("Activo", typeof(bool));
t.Rows.Add(1,"Café Andino Premium",2,1,"500 g",45.9m,120,30,20,false,true);
t.Rows.Add(2,"Salsa de Ají Amarillo",4,2,"300 ml",12.5m,200,50,30,false,true);
t.Rows.Add(3,"Mermelada de Aguaymanto",5,3,"250 g",15.0m,80,20,15,false,true);
t.Rows.Add(4,"Queso Fresco Andino",1,4,"1 kg",22.0m,60,10,10,false,true);
t.Rows.Add(5,"Chorizo Ahumado",3,5,"500 g",18.75m,90,25,20,false,true);
ds.Tables.Add(t);
t = new DataTable("Pedidos");
t.Columns.Add("PedidoID", typeof(int));
t.Columns.Add("ClienteID", typeof(int));
t.Columns.Add("EmpleadoID", typeof(int));
t.Columns.Add("FechaPedido", typeof(DateTime));
t.Columns.Add("FechaRequerida", typeof(DateTime));
t.Columns.Add("FechaEnvio", typeof(DateTime));
t.Columns.Add("TransportistaID", typeof(int));
t.Columns.Add("Destinatario", typeof(string));
t.Columns.Add("CiudadDestino", typeof(string));
t.Columns.Add("PaisDestino", typeof(string));
t.Columns.Add("Activo", typeof(bool));
t.Rows.Add(1,1,1,DateTime.Parse("2026-08-10", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-20", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-15", System.Globalization.CultureInfo.InvariantCulture),1,"Comercial Andina SAC","Lima","Perú",true);
t.Rows.Add(2,2,3,DateTime.Parse("2026-08-12", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-22", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-18", System.Globalization.CultureInfo.InvariantCulture),3,"Supermercados del Norte","Trujillo","Perú",true);
t.Rows.Add(3,3,2,DateTime.Parse("2026-08-15", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-25", System.Globalization.CultureInfo.InvariantCulture),DBNull.Value,4,"Distribuidora Sureña EIRL","Arequipa","Perú",true);
t.Rows.Add(4,4,4,DateTime.Parse("2026-08-20", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-30", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-26", System.Globalization.CultureInfo.InvariantCulture),5,"Minimarket Central","Cusco","Perú",true);
t.Rows.Add(5,5,5,DateTime.Parse("2026-08-22", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-09-01", System.Globalization.CultureInfo.InvariantCulture),DateTime.Parse("2026-08-28", System.Globalization.CultureInfo.InvariantCulture),2,"Tiendas Express SAC","Chiclayo","Perú",true);
ds.Tables.Add(t);
t = new DataTable("DetallePedidos");
t.Columns.Add("PedidoID", typeof(int));
t.Columns.Add("ProductoID", typeof(int));
t.Columns.Add("PrecioUnidad", typeof(decimal));
t.Columns.Add("Cantidad", typeof(int));
t.Columns.Add("Descuento", typeof(decimal));
t.Rows.Add(1,1,45.9m,10,0.0m);
t.Rows.Add(2,2,12.5m,25,0.05m);
t.Rows.Add(3,3,15.0m,15,0.0m);
t.Rows.Add(4,4,22.0m,8,0.1m);
t.Rows.Add(5,5,18.75m,12,0.0m);
ds.Tables.Add(t);
t = new DataTable("Reporte");
t.Columns.Add("PedidoID",typeof(int)); t.Columns.Add("FechaPedido",typeof(DateTime)); t.Columns.Add("Destinatario");
t.Columns.Add("ProductoID",typeof(int));t.Columns.Add("NombreProducto");t.Columns.Add("PrecioUnidad",typeof(decimal));
t.Columns.Add("Cantidad",typeof(int));t.Columns.Add("Descuento",typeof(decimal));t.Columns.Add("Importe",typeof(decimal));
foreach(DataRow d in ds.Tables["DetallePedidos"].Rows) {
 var p = ds.Tables["Pedidos"].Select("PedidoID = "+d["PedidoID"])[0];
 var pr = ds.Tables["Productos"].Select("ProductoID = "+d["ProductoID"])[0];
 var amount = Math.Round(Convert.ToDecimal(d["PrecioUnidad"])*Convert.ToInt32(d["Cantidad"])*(1-Convert.ToDecimal(d["Descuento"])),2,MidpointRounding.AwayFromZero);
 t.Rows.Add(p["PedidoID"],p["FechaPedido"],p["Destinatario"],pr["ProductoID"],pr["NombreProducto"],d["PrecioUnidad"],d["Cantidad"],d["Descuento"],amount);
} ds.Tables.Add(t); return ds; } } }
